### PR TITLE
Update map page text

### PR DESCRIPTION
**Pull request by sandlerben**

### CODE REVIEW

**Comment by sandlerben** [comment]
Anosha is doing the about page, that's a good idea for her.

Let me play with the layout and verify on several browsers.

**Comment by sandlerben** [comment]
Yeah, I'm not super sure of what to do here. I made the console vertically scrollable but no matter how much I shrink the year/month it's not all going to fit. 

image

**Comment by sandlerben** [comment]
One option is move the blurb about downloading/about to be right below the "using machine learning..." and above the key.

**Comment by yoninachmany** [comment]
@sandlerben i like that idea

**Pull request merged**
